{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 7,
    "last_updated": "2025-11-01T04:31:35.118684",
    "severity_distribution": {
      "critical": 1,
      "high": 2,
      "medium": 1,
      "low": 0,
      "none": 3
    }
  },
  "cves": [
    {
      "id": "CVE-2025-48983",
      "publishedDate": "2025-10-30T23:33:01.993Z",
      "lastModifiedDate": "2025-11-01T03:55:50.741Z",
      "description": "A vulnerability in the Mount service of Veeam Backup & Replication, which allows for remote code execution (RCE) on the Backup infrastructure hosts by an authenticated domain user.",
      "severity": 10,
      "references": [
        {
          "url": "https://www.veeam.com/kb4771",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "defaultStatus": "unaffected",
          "vendor": "Veeam",
          "product": "Backup and Replication",
          "versions": [
            {
              "version": "12.3.2",
              "status": "affected",
              "lessThanOrEqual": "12.3.2",
              "versionType": "semver"
            }
          ]
        }
      ],
      "problemType": [],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-33003",
      "publishedDate": "2025-10-31T13:04:31.204Z",
      "lastModifiedDate": "2025-11-01T03:55:53.966Z",
      "description": "IBM InfoSphere Information Server 11.7.0.0 through 11.7.1.6 could allow a non-root user to gain higher privileges/capabilities within the scope of a container due to execution with unnecessary privileges.",
      "severity": 7.8,
      "references": [
        {
          "url": "https://www.ibm.com/support/pages/node/7246684",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "cpes": [
            "cpe:2.3:a:ibm:infosphere_information_server:11.7.0.0:*:*:*:*:*:*:*",
            "cpe:2.3:a:ibm:infosphere_information_server:11.7.1.6:*:*:*:*:*:*:*"
          ],
          "defaultStatus": "unaffected",
          "product": "InfoSphere Information Server",
          "vendor": "IBM",
          "versions": [
            {
              "lessThanOrEqual": "11.7.1.6",
              "status": "affected",
              "version": "11.7.0.0",
              "versionType": "semver"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-250 Execution with Unnecessary Privileges"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-36137",
      "publishedDate": "2025-10-30T18:53:32.576Z",
      "lastModifiedDate": "2025-11-01T03:55:53.155Z",
      "description": "IBM Sterling Connect Direct for Unix 6.2.0.7 through 6.2.0.9 iFix004, 6.4.0.0 through 6.4.0.2 iFix001, and 6.3.0.2 through 6.3.0.5 iFix002 incorrectly assigns permissions for maintenance tasks to Control Center Director (CCD) users that could allow a privileged user to escalate their privileges further due to unnecessary privilege assignment for post update scripts.",
      "severity": 7.2,
      "references": [
        {
          "url": "https://www.ibm.com/support/pages/node/7249678",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "cpes": [
            "cpe:2.3:a:ibm:sterling_connect\\:direct:6.2.0.7:*:*:*:*:unix:*:*",
            "cpe:2.3:a:ibm:sterling_connect\\:direct:6.2.0.9:ifix004:*:*:*:unix:*:*",
            "cpe:2.3:a:ibm:sterling_connect\\:direct:6.4.0.0:*:*:*:*:unix:*:*",
            "cpe:2.3:a:ibm:sterling_connect\\:direct:6.4.0.2.:ifix001:*:*:*:unix:*:*",
            "cpe:2.3:a:ibm:sterling_connect\\:direct:6.3.0.2:*:*:*:*:*:*:*",
            "cpe:2.3:a:ibm:sterling_connect\\:direct:6.3.0.5.:ifix002:*:*:*:unix:*:*"
          ],
          "defaultStatus": "unaffected",
          "product": "Sterling Connect:Direct for Unix",
          "vendor": "IBM",
          "versions": [
            {
              "lessThanOrEqual": "6.2.0.9 iFix004",
              "status": "affected",
              "version": "6.2.0.7",
              "versionType": "semver"
            },
            {
              "lessThanOrEqual": "6.4.0.2 iFix001",
              "status": "affected",
              "version": "6.4.0.0",
              "versionType": "semver"
            },
            {
              "lessThanOrEqual": "6.3.0.5 iFix002",
              "status": "affected",
              "version": "6.3.0.2",
              "versionType": "semver"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-250 Execution with Unnecessary Privileges"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-60711",
      "publishedDate": "2025-10-31T19:29:01.444Z",
      "lastModifiedDate": "2025-11-01T03:55:54.744Z",
      "description": "Protection mechanism failure in Microsoft Edge (Chromium-based) allows an unauthorized attacker to execute code over a network.",
      "severity": 6.3,
      "references": [
        {
          "url": "https://msrc.microsoft.com/update-guide/vulnerability/CVE-2025-60711",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "Microsoft",
          "product": "Microsoft Edge (Chromium-based)",
          "platforms": [
            "Unknown"
          ],
          "versions": [
            {
              "version": "1.0.0.0",
              "lessThan": "142.0.3595.53",
              "versionType": "custom",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-693: Protection Mechanism Failure"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-48982",
      "publishedDate": "2025-10-30T23:33:01.695Z",
      "lastModifiedDate": "2025-11-01T03:55:49.438Z",
      "description": "This vulnerability in Veeam Agent for Microsoft Windows allows for Local Privilege Escalation if a system administrator is tricked into restoring a malicious file.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://www.veeam.com/kb4771",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "defaultStatus": "unaffected",
          "vendor": "Veeam",
          "product": "Agent for Microsoft Windows",
          "versions": [
            {
              "version": "4.7.2",
              "status": "affected",
              "lessThanOrEqual": "4.7.2",
              "versionType": "semver"
            }
          ]
        }
      ],
      "problemType": [],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-48984",
      "publishedDate": "2025-10-30T23:31:34.218Z",
      "lastModifiedDate": "2025-11-01T03:55:51.554Z",
      "description": "A vulnerability allowing remote code execution (RCE) on the Backup Server by an authenticated domain user.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://www.veeam.com/kb4771",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "defaultStatus": "unaffected",
          "vendor": "Veeam",
          "product": "Backup and Replication",
          "versions": [
            {
              "version": "12.3.2",
              "status": "affected",
              "lessThanOrEqual": "12.3.2",
              "versionType": "semver"
            }
          ]
        }
      ],
      "problemType": [],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-12060",
      "publishedDate": "2025-10-30T17:10:43.868Z",
      "lastModifiedDate": "2025-11-01T03:55:52.355Z",
      "description": "The keras.utils.get_file API in Keras, when used with the extract=True option for tar archives, is vulnerable to a path traversal attack. The utility uses Python's tarfile.extractall function without the filter=\"data\" feature. A remote attacker can craft a malicious tar archive containing special symlinks, which, when extracted, allows them to write arbitrary files to any location on the filesystem outside of the intended destination folder. This vulnerability is linked to the underlying Python tarfile weakness, identified as CVE-2025-4517. Note that upgrading Python to one of the versions that fix CVE-2025-4517 (e.g. Python 3.13.4) is not enough. One additionally needs to upgrade Keras to a version with the fix (Keras 3.12).",
      "severity": "N/A",
      "references": [
        {
          "url": "https://github.com/keras-team/keras/pull/21760",
          "type": "reference"
        },
        {
          "url": "https://github.com/keras-team/keras/security/advisories/GHSA-hjqc-jx6g-rwp9",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "collectionURL": "https://github.com/keras-team/keras/",
          "defaultStatus": "unaffected",
          "packageName": "util",
          "product": "Keras",
          "programFiles": [
            "get_file"
          ],
          "vendor": "Keras",
          "versions": [
            {
              "lessThanOrEqual": "3.11.3",
              "status": "affected",
              "version": "3.0.0",
              "versionType": "semver"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-22 Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}