{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 9,
    "last_updated": "2025-09-25T14:29:30.562705",
    "severity_distribution": {
      "critical": 0,
      "high": 2,
      "medium": 1,
      "low": 0,
      "none": 6
    }
  },
  "cves": [
    {
      "id": "CVE-2025-10948",
      "publishedDate": "2025-09-25T14:02:07.376Z",
      "lastModifiedDate": "2025-09-25T14:17:02.592Z",
      "description": "A vulnerability has been found in MikroTik RouterOS 7. This affects the function parse_json_element of the file /rest/ip/address/print of the component libjson.so. The manipulation leads to buffer overflow. The attack is possible to be carried out remotely. The exploit has been disclosed to the public and may be used. The vendor was contacted early about this disclosure but did not respond in any way.",
      "severity": 8.8,
      "references": [
        {
          "url": "https://vuldb.com/?id.325818",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?ctiid.325818",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?submit.652387",
          "type": "reference"
        },
        {
          "url": "https://github.com/a2ure123/libjson-unicode-buffer-overflow-poc",
          "type": "poc"
        },
        {
          "url": "https://github.com/a2ure123/libjson-unicode-buffer-overflow-poc#technical-proof-of-concept",
          "type": "poc"
        }
      ],
      "affected": [
        {
          "vendor": "MikroTik",
          "product": "RouterOS",
          "versions": [
            {
              "version": "7",
              "status": "affected"
            }
          ],
          "modules": [
            "libjson.so"
          ]
        }
      ],
      "problemType": [
        "Buffer Overflow",
        "Memory Corruption"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-59839",
      "publishedDate": "2025-09-25T13:56:13.804Z",
      "lastModifiedDate": "2025-09-25T14:19:53.153Z",
      "description": "The EmbedVideo Extension is a MediaWiki extension which adds a parser function called #ev and various parser tags for embedding video clips from various video sharing services. In versions 4.0.0 and prior, the EmbedVideo extension allows adding arbitrary attributes to an HTML element, allowing for stored XSS through wikitext. This issue has been patched via commit 4e075d3.",
      "severity": 8.6,
      "references": [
        {
          "url": "https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/security/advisories/GHSA-4j5h-mvj3-m48v",
          "type": "reference"
        },
        {
          "url": "https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/commit/4e075d3dc9a15a3ee53f449a684d5ab847e52f01",
          "type": "reference"
        },
        {
          "url": "https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/blob/440fb331a84b2050f4cc084c1d31d58a1d1c202d/resources/ext.embedVideo.videolink.js#L5-L20",
          "type": "reference"
        },
        {
          "url": "https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/blob/440fb331a84b2050f4cc084c1d31d58a1d1c202d/resources/modules/iframe.js#L139-L155",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "StarCitizenWiki",
          "product": "mediawiki-extensions-EmbedVideo",
          "versions": [
            {
              "version": "<= 4.0.0",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-59426",
      "publishedDate": "2025-09-25T14:00:09.629Z",
      "lastModifiedDate": "2025-09-25T14:18:27.175Z",
      "description": "Lobe Chat is an open-source artificial intelligence chat framework. Prior to version 1.130.1, the project's OIDC redirect handling logic constructs the host and protocol of the final redirect URL based on the X-Forwarded-Host or Host headers and the X-Forwarded-Proto value. In deployments where a reverse proxy forwards client-supplied X-Forwarded-* headers to the origin as-is, or where the origin trusts them without validation, an attacker can inject an arbitrary host and trigger an open redirect that sends users to a malicious domain. This issue has been patched in version 1.130.1.",
      "severity": 4.3,
      "references": [
        {
          "url": "https://github.com/lobehub/lobe-chat/security/advisories/GHSA-xph5-278p-26qx",
          "type": "reference"
        },
        {
          "url": "https://github.com/lobehub/lobe-chat/commit/70f52a3c1fadbd41a9db0e699d1e44d9965de445",
          "type": "reference"
        },
        {
          "url": "https://github.com/lobehub/lobe-chat/blob/aa841a3879c30142720485182ad62aa0dbd74edc/src/app/(backend)/oidc/consent/route.ts#L113-L127",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "lobehub",
          "product": "lobe-chat",
          "versions": [
            {
              "version": "< 1.130.1",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-601: URL Redirection to Untrusted Site ('Open Redirect')"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-59823",
      "publishedDate": "2025-09-25T14:17:37.607Z",
      "lastModifiedDate": "2025-09-25T14:17:37.607Z",
      "description": "Project Gardener implements the automated management and operation of Kubernetes clusters as a service. Code injection may be possible in Gardener Extensions for AWS providers prior to version 1.64.0, Azure providers prior to version 1.55.0, OpenStack providers prior to version 1.49.0, and GCP providers prior to version 1.46.0. This vulnerability could allow a user with administrative privileges for a Gardener project to obtain control over the seed cluster where the shoot cluster is managed. This affects all Gardener installations where Terraformer is used/can be enabled for infrastructure provisioning with any of the affected components. This issue has been patched in Gardener Extensions for AWS providers version 1.64.0, Azure providers version 1.55.0, OpenStack providers version 1.49.0, and GCP providers version 1.46.0.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://github.com/gardener/gardener-extension-provider-aws/security/advisories/GHSA-227x-7mh8-3cf6",
          "type": "reference"
        },
        {
          "url": "https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.64.0",
          "type": "reference"
        },
        {
          "url": "https://github.com/gardener/gardener-extension-provider-azure/releases/tag/v1.55.0",
          "type": "reference"
        },
        {
          "url": "https://github.com/gardener/gardener-extension-provider-gcp/releases/tag/v1.46.0",
          "type": "reference"
        },
        {
          "url": "https://github.com/gardener/gardener-extension-provider-openstack/releases/tag/v1.49.0",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "gardener",
          "product": "gardener-extension-provider-aws",
          "versions": [
            {
              "version": "< 1.64.0",
              "status": "affected"
            },
            {
              "version": "< 1.55.0",
              "status": "affected"
            },
            {
              "version": "< 1.49.0",
              "status": "affected"
            },
            {
              "version": "< 1.46.0",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-94: Improper Control of Generation of Code ('Code Injection')"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-46150",
      "publishedDate": "2025-09-25T00:00:00.000Z",
      "lastModifiedDate": "2025-09-25T14:20:02.992Z",
      "description": "In PyTorch before 2.7.0, when torch.compile is used, FractionalMaxPool2d has inconsistent results.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://github.com/pytorch/pytorch/issues/141538",
          "type": "reference"
        },
        {
          "url": "https://github.com/pytorch/pytorch/issues/141538#issuecomment-2537424658",
          "type": "reference"
        },
        {
          "url": "https://github.com/pytorch/pytorch/pull/144395",
          "type": "reference"
        },
        {
          "url": "https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "n/a",
          "product": "n/a",
          "versions": [
            {
              "version": "n/a",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "n/a"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-46148",
      "publishedDate": "2025-09-25T00:00:00.000Z",
      "lastModifiedDate": "2025-09-25T14:17:49.517Z",
      "description": "In PyTorch through 2.6.0, when eager is used, nn.PairwiseDistance(p=2) produces incorrect results.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://github.com/pytorch/pytorch/issues/151198",
          "type": "reference"
        },
        {
          "url": "https://gist.github.com/shaoyuyoung/65a587a579dfdff887b9b35bb79b9093",
          "type": "reference"
        },
        {
          "url": "https://github.com/pytorch/pytorch/pull/152993",
          "type": "reference"
        },
        {
          "url": "https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "n/a",
          "product": "n/a",
          "versions": [
            {
              "version": "n/a",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "n/a"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-46152",
      "publishedDate": "2025-09-25T00:00:00.000Z",
      "lastModifiedDate": "2025-09-25T14:21:10.172Z",
      "description": "In PyTorch before 2.7.0, bitwise_right_shift produces incorrect output for certain out-of-bounds values of the \"other\" argument.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://github.com/pytorch/pytorch/issues/143555",
          "type": "reference"
        },
        {
          "url": "https://github.com/pytorch/pytorch/pull/143635",
          "type": "reference"
        },
        {
          "url": "https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "n/a",
          "product": "n/a",
          "versions": [
            {
              "version": "n/a",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "n/a"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-46153",
      "publishedDate": "2025-09-25T00:00:00.000Z",
      "lastModifiedDate": "2025-09-25T14:21:41.597Z",
      "description": "PyTorch before 3.7.0 has a bernoulli_p decompose function in decompositions.py even though it lacks full consistency with the eager CPU implementation, negatively affecting nn.Dropout1d, nn.Dropout2d, and nn.Dropout3d for fallback_random=True.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://github.com/pytorch/pytorch/issues/142853",
          "type": "reference"
        },
        {
          "url": "https://github.com/pytorch/pytorch/pull/143460",
          "type": "reference"
        },
        {
          "url": "https://gist.github.com/shaoyuyoung/e636f2e7a306105b7e96809e2b85c28a",
          "type": "reference"
        },
        {
          "url": "https://github.com/pytorch/pytorch/compare/v2.6.0...v2.7.0",
          "type": "reference"
        },
        {
          "url": "https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "n/a",
          "product": "n/a",
          "versions": [
            {
              "version": "n/a",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "n/a"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-46149",
      "publishedDate": "2025-09-25T00:00:00.000Z",
      "lastModifiedDate": "2025-09-25T14:19:13.387Z",
      "description": "In PyTorch before 2.7.0, when inductor is used, nn.Fold has an assertion error.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://github.com/pytorch/pytorch/issues/147848",
          "type": "reference"
        },
        {
          "url": "https://github.com/pytorch/pytorch/pull/147961",
          "type": "reference"
        },
        {
          "url": "https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "n/a",
          "product": "n/a",
          "versions": [
            {
              "version": "n/a",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "n/a"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}