{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 1,
    "last_updated": "2025-05-18T20:10:49.642597",
    "severity_distribution": {
      "critical": 0,
      "high": 0,
      "medium": 0,
      "low": 1,
      "none": 0
    }
  },
  "cves": [
    {
      "id": "CVE-2025-4894",
      "publishedDate": "2025-05-18T20:00:09.114Z",
      "lastModifiedDate": "2025-05-18T20:00:09.114Z",
      "description": "A vulnerability classified as problematic was found in calmkart Django-sso-server up to 057247929a94ffc358788a37ab99e391379a4d15. This vulnerability affects the function gen_rsa_keys of the file common/crypto.py. The manipulation leads to inadequate encryption strength. The attack can be initiated remotely. The complexity of an attack is rather high. The exploitation appears to be difficult. This product is using a rolling release to provide continious delivery. Therefore, no version details for affected nor updated releases are available.",
      "severity": 3.7,
      "references": [
        {
          "url": "https://vuldb.com/?id.309448",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?ctiid.309448",
          "type": "reference"
        },
        {
          "url": "https://vuldb.com/?submit.578019",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "calmkart",
          "product": "Django-sso-server",
          "versions": [
            {
              "version": "057247929a94ffc358788a37ab99e391379a4d15",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "Inadequate Encryption Strength",
        "Cryptographic Issues"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}