{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 1,
    "last_updated": "2025-06-24T06:20:46.713391",
    "severity_distribution": {
      "critical": 0,
      "high": 1,
      "medium": 0,
      "low": 0,
      "none": 0
    }
  },
  "cves": [
    {
      "id": "CVE-2025-2962",
      "publishedDate": "2025-06-24T05:32:11.287Z",
      "lastModifiedDate": "2025-06-24T05:32:11.287Z",
      "description": "A denial-of-service issue in the dns implemenation could cause an infinite loop.",
      "severity": 8.2,
      "references": [
        {
          "url": "https://github.com/zephyrproject-rtos/zephyr/security/advisories/GHSA-2qp5-c2vq-g2ww",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "defaultStatus": "unaffected",
          "packageName": "Zephyr",
          "product": "Zephyr",
          "repo": "https://github.com/zephyrproject-rtos/zephyr",
          "vendor": "zephyrproject-rtos",
          "versions": [
            {
              "lessThanOrEqual": "4.1.0",
              "status": "affected",
              "version": "*",
              "versionType": "git"
            },
            {
              "lessThanOrEqual": "3.7.1",
              "status": "affected",
              "version": "*",
              "versionType": "git"
            }
          ]
        }
      ],
      "problemType": [
        "Loop with Unreachable Exit Condition ('Infinite Loop')"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}