{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 1,
    "last_updated": "2025-03-27T02:54:25.033101",
    "severity_distribution": {
      "critical": 0,
      "high": 0,
      "medium": 0,
      "low": 1,
      "none": 0
    }
  },
  "cves": [
    {
      "id": "CVE-2025-31160",
      "publishedDate": "2025-03-26T00:00:00.000Z",
      "lastModifiedDate": "2025-03-27T02:28:51.774Z",
      "description": "atop through 2.11.0 allows local users to cause a denial of service (e.g., assertion failure and application exit) or possibly have unspecified other impact by running certain types of unprivileged processes while a different user runs atop.",
      "severity": 2.9,
      "references": [
        {
          "url": "https://rachelbythebay.com/w/2025/03/26/atop/",
          "type": "reference"
        },
        {
          "url": "https://news.ycombinator.com/item?id=43485980",
          "type": "reference"
        },
        {
          "url": "https://news.ycombinator.com/item?id=43477057",
          "type": "reference"
        },
        {
          "url": "https://github.com/Atoptool/atop",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "defaultStatus": "unknown",
          "product": "atop",
          "vendor": "atop project",
          "versions": [
            {
              "lessThanOrEqual": "2.11.0",
              "status": "affected",
              "version": "0",
              "versionType": "semver"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-617 Reachable Assertion"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}