{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 1,
    "last_updated": "2025-02-26T17:56:54.853372",
    "severity_distribution": {
      "critical": 0,
      "high": 0,
      "medium": 0,
      "low": 0,
      "none": 1
    }
  },
  "cves": [
    {
      "id": "CVE-2025-1716",
      "publishedDate": "2025-02-26T14:51:38.085Z",
      "lastModifiedDate": "2025-02-26T17:35:25.570Z",
      "description": "picklescan before 0.0.21 does not treat 'pip' as an unsafe global. An attacker could craft a malicious model that uses Pickle to pull in a malicious PyPI package (hosted, for example, on pypi.org or GitHub) via `pip.main()`. Because pip is not a restricted global, the model, when scanned with picklescan, would pass security checks and appear to be safe, when it could instead prove to be problematic.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://sites.google.com/sonatype.com/vulnerabilities/cve-2025-1716",
          "type": "reference"
        },
        {
          "url": "https://github.com/mmaitre314/picklescan/commit/78ce704227c51f070c0c5fb4b466d92c62a7aa3d",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "collectionURL": "https://pypi.org/project/picklescan/",
          "defaultStatus": "unaffected",
          "product": "picklescan",
          "repo": "https://github.com/mmaitre314/picklescan",
          "vendor": "mmaitre314",
          "versions": [
            {
              "lessThanOrEqual": "0.0.20",
              "status": "affected",
              "version": "0.0.1",
              "versionType": "semver"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-184 Incomplete List of Disallowed Inputs"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}